config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get  '/signup'  => 'users#new'
  post '/signup'  => 'users#create'
  get  '/login'   => 'sessions#new'
  post '/login'   => 'sessions#create'
  delete '/logout'=> 'sessions#destroy'
  resources :users
  resources :posts, only: [:new, :create, :index]
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

	before_create { self.remember_token = digest(new_token) }

	has_many :posts, dependent: :destroy

	validates :username, presence: true
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
     validates :email, presence: true, length: { maximum: 255 },
                       format: { with: VALID_EMAIL_REGEX },
                       uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
	has_secure_password

	def new_token
		SecureRandom.urlsafe_base64
	end

	def digest(token)
		Digest::SHA1.hexdigest(token)
	end

	def remember
		self.remember_token = new_token
		update_attribute(:remember_token, digest(remember_token))
	end

	def forget
		update_attribute(:remember_token, nil)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:destroy, :create]
  before_action :correct_user, only: :destroy
  def create
    @new_post = current_user.posts.build(post_params)
    @new_post.save
    redirect_to root_path
  end
  def index
    @posts = Post.all
  end
  def new
    @post = Post.new
  end
  private
    def post_params
      params.require(:post).permit(:content)
    end

    def logged_in_user
      unless logged_in?
        redirect_to login_path
      end
    end

    def correct_user
      user = Post.find(params[:id]).user
      unless current_user? user
        redirect_to root_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      login @user
      redirect_to @user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    logout if logged_in?
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all
    @new_post = Post.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_url unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user?(user)
    current_user == user
  end

  def current_user
    if (user_id = User.find_by(id: session[:user_id]))
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        login user
        @current_user = user
      end
    end
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    forget(current_user)
    @current_user = nil
    session.delete(:user_id)
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home",   root_path %></li>
      <% if logged_in? %>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
        </li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
      <% end %>
    </ul>
  </nav>
<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<h3>Posts</h3>
<% if logged_in? %>
	<%= link_to 'Log Out', logout_path, method: :delete %>
	<%= link_to "Create Post", new_post_path %>
<% else %>
	<%= link_to "Log In", login_path %>
<% end %>

<% @posts.each do |p|
  authorName = "Log in to see who wrote this!"
  if logged_in?
    authorName = p.user.username
  end
%>
<div class="title">Tutle</div>
<div class="body"><%= p.content %></div>
<div class="author">
  <%= authorName %>
</div>
</br></br>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, url: posts_path do |f| %>
  <%= f.text_area :content, placeholder: "Got anything to share?" %>
  <%= f.submit "Post", class: 'btn btn-primary' %>
<% end if logged_in? %>

app/views/static_pages/home.html.erb
<% unless logged_in? %>
<div id="reminder" class="center jumbotron">
  <h1>Welcome to <strong>Members Only!</strong></h1>
  <h2>
    Click <%= link_to "here", "#" %> to log in. Not yet a member? Click the link below to register.
  </h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% end %>

<div class="row">
  <aside class="col-md-2">

    <section class="user_info">
      <% if logged_in? %>
      <h1>
        <%= link_to current_user.username, current_user %>
      </h1>
      <% end %>
    </section>
  </aside>

  <div class="col-md-6">
    <ul class="posts">
      <%= form_for @new_post, url: posts_path do |f| %>
        <%= f.text_area :content, placeholder: "Got anything to share?" %>
        <%= f.submit "Post", class: 'btn btn-primary' %>
      <% end if logged_in? %>
    </ul>
  </div>

</div>

app/views/users/_post.html.erb
<div>
  <p class="comment"><%= post.content %></p>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= link_to "Log out", logout_path, method: :delete %>
<div class="row">
  <aside class="col-md-3">
    <section class="user_info">
      <h1>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
  <% if logged_in? %>
    <h3>Posts (<%= @user.posts.size %>)</h3>
    <%= render partial: 'users/post', collection: @user.posts %>
  <% end %>
</div>